name: Generate Archi HTML Report

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  archi_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Archi Report
        uses: WoozyMasta/archimate-ci-image@5.7.0-1.0.6
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          archiHtmlReportEnabled: true
          archiCsvReportEnabled: false
          archiJasperReportEnabled: false
          archiExportModelEnabled: true
          
